services:
  - type: web
    name: grafana
    env: docker
    dockerfilePath: ./Dockerfile.render
    envVars:
      - key: GF_SECURITY_ADMIN_USER
        value: admin
      - key: GF_SECURITY_ADMIN_PASSWORD
        value: Admin123
      - key: GF_SECURITY_SECRET_KEY
        value: MySecretKey12345
      - key: GF_LOG_LEVEL
        value: info
      - key: GF_ANALYTICS_REPORTING_ENABLED
        value: false
