apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m
      queryTimeout: 60s
      timeInterval: 15s

  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: grafana
    user: grafana
    secureJsonData:
      password: grafana_password
    jsonData:
      httpMode: POST
      version: InfluxQL
      timeInterval: 10s
      maxSeries: 1000

  - name: MySQL
    type: mysql
    access: proxy
    url: mysql:3306
    database: grafana
    user: grafana
    secureJsonData:
      password: grafana_password
    jsonData:
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      timezone: UTC
